[project]
name = "library-manager"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
dependencies = [
    "streamlit>=1.25.0"
]

